apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.global.namespace | default .Values.namespace  }}
spec:
  replicas: {{ .Values.global.tessell_iam.replicas | default .Values.replicas  }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8082"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      nodeSelector:
        beta.kubernetes.io/instance-type: {{ .Values.global.instance_type | default .Values.instance_type }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values: 
                      - {{ .Chart.Name }}
              topologyKey: "kubernetes.io/hostname"
      containers:
        - envFrom:
            - secretRef:
                name: {{ .Values.global.tessell_common_secret }}
            - configMapRef:
                name: {{.Values.global.tessell_common_config}}
            - configMapRef:
                name: {{.Values.tessell_iam_config}}
          image: "{{ .Values.global.docker_repository }}/{{ .Chart.Name }}-service:{{ .Chart.AppVersion }}"
          imagePullPolicy: Always
          name: {{ .Chart.Name }}
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8082
              scheme: HTTP
            initialDelaySeconds: 75
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8082
              scheme: HTTP
            initialDelaySeconds: 75
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          resources:
            requests:
              memory: {{ .Values.global.tessell_iam.requests_memory | default .Values.requests_memory  }}
              cpu: {{ .Values.global.tessell_iam.requests_cpu | default .Values.requests_cpu  }}
            limits:
              memory: {{ .Values.global.tessell_iam.limits_memory | default .Values.limits_memory  }}
              cpu: {{ .Values.global.tessell_iam.limits_cpu | default .Values.limits_cpu  }}
      imagePullSecrets:
        - name: {{.Values.global.docker_secret_name}}
