apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ .Chart.Name }}-pdb
  namespace: {{ .Values.global.namespace | default .Values.namespace  }}
spec:
  minAvailable: 100%
  selector:
    matchLabels:
      app: {{ .Chart.Name }}