apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.global.namespace | default .Values.namespace  }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/actuator/prometheus"
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8082
  selector:
    app: {{ .Chart.Name }}