---
name: Auto Merge Double Commit PRs
on:
  pull_request:
    types: [ opened, synchronize ]
    branches:
      - 'main'
      - 'rel-*'

jobs:
  auto-merge:
    runs-on: self-hosted
    env:
       SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL  }}
    if: contains(github.event.pull_request.head.ref, 'double_commit')
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.2
        with:
          token: ${{ secrets.PIPELINES_REPO_TOKEN  }}

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"

      - name: Auto approve
        uses: juliangruber/approve-pull-request-action@v2
        with:
          github-token: ${{ secrets.CI_APPROVER_TOKEN  }}
          number: "${{ github.event.number }}"

      - name: Enable Auto Merge
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.PIPELINES_REPO_TOKEN  }}
          pull-request-number: "${{ github.event.number }}"
          merge-method: squash

     
      - name: Slack Notification
        uses: act10ns/slack@v1.5.0
        with:
           status: ${{ job.status }}
           steps: ${{ toJson(steps) }}
           channel: ${{ secrets.SLACK_DEVOPS_CHANNEL  }}
        if: failure()

