
name: Deploy
on:
  repository_dispatch:
    types: [my-event]
    
  workflow_dispatch:
  push:
    branches:
      - 'rel-*'
      - 'main'
  
  check_suite:
    types:
      - completed
      
  status: {}
    
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.ref }}
      - run: echo ${{ github.event.client_payload.sha }}
      
      
      - name: Install deps
        shell: bash
        run: |
          python -m pip install gitpython;
    
      - uses: actions/checkout@v3
      - name: push tag
        shell: bash
        run: |
          python3 .github/scripts/helper.py ${{ github.event.client_payload.sha}} 
          
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PIPELINES_REPO_TOKEN  }}
          commit-message: 'build: update distribution'
          title: helm_values_update
          body: |
            - Updates the distribution for changes on `main`
            Auto-generated by [create-pull-request][1]
            [1]: https://github.com/peter-evans/create-pull-request
          branch: TS-helm_values_update
 
